govau/chameleon

public/main.js
src/index.js

Added basic error check to page template

---

.circleci/config.yml
package.json

Starter for CI process, will setup deployment to cloud.gov.au soon
Links to #2

[WIP] Added circleci starter

---

package-lock.json
package.json
src/index.js

Previously a user coudln't submit a non standard color type like `#212121` due to URI encoding of the symbols.

Imported urldecode module to decode color value

---

assets/html/404.html
src/index.js

Added 404 page to capture non-exist path

---

test/unit/index.spec.js

Add unit test for multiple inputs

---

.deploy/manifest-dev.yml
.deploy/manifest-prod.yml

Specifies bound CF service for prod / dev.
Updates `buildpack` key to modern `buildpacks`

Fix CF ups

---

assets/sass/main.scss
templates/basic/index.html

Updated side nav to use button since we updated accordion.
Also changed some SASS in reference to govau/uikit-starter#54

Update sass and accordion button

---

.deploy/manifest-dev.yml
.deploy/manifest-prod.yml
assets/html/404.html
package.json
src/helpers.js
src/html.js
src/server.js
src/settings.js
src/style.js
test/unit/html.spec.js

Fix #36 
Also Renamed index.js -> server.js 
Created `helper.js` file to contain promisify `node-sass` render function

Utilised Fs.promises experimental library to switch sync functions to async

---

.deploy/manifest-dev.yml
.deploy/manifest-prod.yml

Going to trial 256M for staging, 512 is so high :(

Increase deployment memory usage

---

.deploy/manifest-dev.yml
.deploy/manifest-prod.yml

Switched form 512->256M for CF deployments

---

CHANGELOG.md
README.md
package.json
src/index.js
src/slack.js
templates/content/index.html
templates/form/index.html
templates/index.html
test/unit/slack.spec.js

- Added Slack message preview URL.
- Spelling tweaks

RC 1.2.0 - Slack improvements

---

package-lock.json
package.json
src/index.js

Seems to add CSP `frame-src` correctly, worth a try:

Remove helmet

---

src/style.js

So that if I enter “    green  “ it won’t crash

trim white space from color strings

---

package-lock.json

Update versions for:
pancake
accordion
side-nav
responsive-media

Update pancake, accordion side-nav, responsive-media dependencies

---

CHANGELOG.md
README.md
package-lock.json
package.json

- Bumped package-lock.json for `pancake`, `pancake-js`, `pancake-json`, `pancake-react` and `pancake-sass`
- Bumped everything else

Bumped deps

---

templates/content/index.html
templates/form/index.html
templates/index.html

- Removed word navigation from main nav in template index.html
- Added aria-labels on the footer and main nav in content and form pages.

Update markup for aria labels on footer and nav elements in Chameleon 

---

package-lock.json
package.json
templates/content/index.html
templates/form/index.html
templates/index.html

Cheers dependabot
- Removed word navigation from main nav in template index.html
- Added aria-labels on the footer and main nav in content and form pages.
fixes #128

Bump deps and aria fixes

---

assets/js/helper.js
assets/js/validate.js
package-lock.json
package.json
templates/form/index.html

Added form component
Updated form template to match with design system starter form
NOTE: form submission was disabled on the form templated, since submitting triggers server side parameter check.

Add form comp, update form template

---

assets/sass/main.scss
templates/form/index.html

Previously the page alert wasn' loading when submitting incomplete form fields. This should now be addressed. Have also removed unnecessary javascript that we were using prevbiously

Add form page alert

---

templates/content/index.html

Side nav position

---

assets/sass/main.scss
package-lock.json
templates/home/index.html

The homepage on the DS starter was updated. Chameleon needed to be updated to reflect this.

Update Homepage to align with DS starter updates
